Podpora pro checkery
kasiopea-org/pisek pull request #61
Opened 2021-04-02 18:57 UTC by vvolhejn

Dva nové testy pro checkery:

- `InputsPassChecker` spustí checker na vygenerované vstupy a zkontroluje, že projde.
- `CheckerDistinguishesSubtasks` je tu proto, aby neprošel checker, který vždycky vrátí returncode 0. Zkontroluje, že kdybychom do subtasku `i` přidali testy ze subtasku `i+1`, checker si bude stěžovat.

Taky jsem přidal odpovídající self-testy, jak pro Kasiopeu tak pro CMS.

Do budoucna bych zvážil, jestli `get_subtasks` nedát do `TaskConfigu` a `in_self_tests` taky.

2021-04-02 21:10 UTC, RichardHladik requested changes
LGTM, kromě těch asi dvou drobností (znovujoinovat v checkeru, [tasks]=>[tests]). Moje zbylé komentáře jsou spíš náměty k diskuzi.
:rocket: :rocket: :rocket:

2021-04-02 21:10 UTC, RichardHladik commented on pisek/tests/test_case.py
> +                "Doporučujeme proto nastavit v sekci [tasks] pole `checker`.",
[tests], ne [tasks]

2021-04-02 21:51 UTC, vvolhejn commented on fixtures/soucet_cms/check.py
> +        numbers = list(map(value_type, line.split(" ")))
Tohle je přímá kopie z Kasiopeích checkerů. Ale máš pravdu, to by chtělo přidat na obě místa.

2021-04-02 21:52 UTC, vvolhejn commented on pisek/tests/test_case.py
> +class CheckerDistinguishesSubtasks(TestCase):
Přidám tam detailnější zprávu k vypsání pokud to spadne.

2021-04-02 21:55 UTC, vvolhejn commented on pisek/tests/test_case.py
> +                    f"subtasků {subtask_i} a {subtask_i + 1} "
Napadlo mě to taky, ale říkal jsem si, že to nechám na jindy.

2021-04-02 21:56 UTC, vvolhejn commented on pisek/tests/test_case.py
> +                res = self.checker.run_on_file(input_file, subtask_i - 1)
Chtěl jsem zachovat `stdout` a `stderr` - níže na to volám `util.quote_process_output(res)`

2021-04-02 21:56 UTC, vvolhejn commented on pisek/tests/test_case.py
> +                "Doporučujeme proto nastavit v sekci [tasks] pole `checker`.",
Ah, pravda

2021-04-02 23:01 UTC, RichardHladik commented on pisek/tests/test_case.py
> +                res = self.checker.run_on_file(input_file, subtask_i - 1)
Jasný, to je určitě důležitý. Já si spíš říkám, jestli prostě tu podmínku `res == 0` neabstrahovat jednořádkovou funkcí, ať je logika (i když triviální) koncentrovaná na jednom místě. Ale asi Tvůj call.

2021-04-03 07:40 UTC, vvolhejn commented on fixtures/soucet_cms/check.py
> +        numbers = list(map(value_type, line.split(" ")))
Tohle je vlastně nakonec asi v pohodě, protože `split` dostane argument `" "`:
```
>>> " a  b".split(" ")
['', 'a', '', 'b']
```
tím pádem přebytečné mezery odchytí buď pokus o cast do intu, nebo pak kontrolu počtu hodnot.

2021-04-03 08:10 UTC, vvolhejn commented on pisek/tests/test_case.py
> +                res = self.checker.run_on_file(input_file, subtask_i - 1)
Nenapadá mě řešení, které by bylo přehlednější než to, jak je to teď, tak to nechám.

2021-04-03 08:24 UTC, merged